In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../../datasets/Bengaluru_House_Data.csv")

In [3]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [4]:
# Remove the society column because it has many missing values
df = df.drop("society", axis=1)

In [5]:
df.head()

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.0,51.00

In [6]:
df.isnull().sum()

area_type         0
availability      0
location          1
size             16
total_sqft        0
bath             73
balcony         609
price             0
dtype: int64

In [8]:
df["balcony"].value_counts()
df["balcony"].describe()

count    12711.000000
mean         1.584376
std          0.817263
min          0.000000
25%          1.000000
50%          2.000000
75%          2.000000
max          3.000000
Name: balcony, dtype: float64

In [9]:
df["balcony"].value_counts()
df["balcony"].describe()

count    12711.000000
mean         1.584376
std          0.817263
min          0.000000
25%          1.000000
50%          2.000000
75%          2.000000
max          3.000000
Name: balcony, dtype: float64

In [10]:
# Fill missing balcony values with the median
df["balcony"] = df["balcony"].fillna(df["balcony"].median())

In [11]:
df["balcony"].isnull().sum()

np.int64(0)

In [14]:
df = df.dropna(subset=["location", "size", "bath"])

In [15]:
df.isnull().sum()

area_type       0
availability    0
location        0
size            0
total_sqft      0
bath            0
balcony         0
price           0
dtype: int64

In [17]:
df.shape

(13246, 8)

In [18]:
df["size"].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom',
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [20]:
def extract_bhk(size):
    return int(size.split(" ")[0])

In [21]:
print(extract_bhk("2 BHK"))
print(extract_bhk("4 Bedroom"))
print(extract_bhk("1 RK"))

2
4
1

In [22]:
df["bhk"] = df["size"].apply(extract_bhk)

In [23]:
df[["size", "bhk"]].head(10)

        size  bhk
0      2 BHK    2
1  4 Bedroom    4
2      3 BHK    3
3      3 BHK    3
4      2 BHK    2
5      2 BHK    2
6      4 BHK    4
7      4 BHK    4
8      3 BHK    3
9  6 Bedroom    6

In [24]:
df["bhk"] = df["size"].apply(extract_bhk)

In [25]:
df[["size", "bhk"]].head(10)

        size  bhk
0      2 BHK    2
1  4 Bedroom    4
2      3 BHK    3
3      3 BHK    3
4      2 BHK    2
5      2 BHK    2
6      4 BHK    4
7      4 BHK    4
8      3 BHK    3
9  6 Bedroom    6